POST http://localhost:3001/tasks
Content-Type: application/json

{
    "title": "Title of the task 555950",
    "dueDate": "2025-01-01T12:00:00Z",
    "description": "This is just another example for the description. This is test description ",
    "priority": "normal",
    "status": "todo"
}